import 'package:flutter/material.dart';

import 'languages.dart';
import 'translated_strings.dart';

class Strings {
  Strings(this.locale);
  final String locale;
  String dayCount(int count) {
    if (locale != 'ar') {
      return '$count ${t(count == 1 ? 'daySingular' : 'days')}';
    }
    if (count == 1) return 'يوم واحد';
    if (count == 2) return 'يومان';
    return '$count ${count == 0 || count % 100 >= 3 && count % 100 <= 10 ? 'أيام' : 'يومًا'}';
  }

  static Strings of(BuildContext context) =>
      Strings(AppLanguages.codeFor(Localizations.localeOf(context)));
  String t(String key) => catalogs[locale]?[key] ?? en[key] ?? key;
  static final Map<String, Map<String, String>> catalogs = {
    'en': en,
    'ar': ar,
    ...translatedStrings.map(
      (code, translations) => MapEntry(code, {...en, ...translations}),
    ),
  };
  static const en = {
    'app': '60-Second Brain Rush',
    'eyebrow': 'YOUR DAILY MENTAL SPARK',
    'sixty': '60 SECOND',
    'brand': 'BRAIN RUSH',
    'tagline': 'How fast is your brain today?',
    'start': 'START RUSH',
    'best': 'Best score',
    'dailyStreak': 'Daily streak',
    'days': 'days',
    'daySingular': 'day',
    'daily': 'Daily Challenge',
    'statistics': 'Statistics',
    'settings': 'Settings',
    'premium': 'REMOVE ADS',
    'premiumDetail': 'One-time purchase · play without interruptions',
    'soon': 'COMING SOON',
    'offline': '60 seconds. Five ways to think. Endless possibility.',
    'score': 'Score',
    'timer': 'Time left',
    'streak': 'Streak',
    'larger': 'Which is larger?',
    'smaller': 'Which is smaller?',
    'fractionLarger': 'Which fraction is larger?',
    'fractionSmaller': 'Which fraction is smaller?',
    'solve': 'Find the answer',
    'odd': 'Which number is odd?',
    'even': 'Which number is even?',
    'sequence': 'Complete the sequence',
    'type_larger': 'QUICK COMPARE',
    'type_arithmetic': 'MENTAL MATH',
    'type_parity': 'ODD OR EVEN',
    'type_sequence': 'PATTERN FINDER',
    'type_fraction': 'FRACTION SPRINT',
    'correct': 'Correct!',
    'incorrect': 'Keep going!',
    'fast': 'FAST!',
    'lightning': 'LIGHTNING!',
    'streakCallout': 'STREAK!',
    'secondsShort': 'SEC',
    'level': 'LV.',
    'xp': 'XP',
    'levelUp': 'LEVEL UP!',
    'newRank': 'NEW RANK',
    'rankWarmUp': 'Warm-Up',
    'rankQuickThinker': 'Quick Thinker',
    'rankSharpMind': 'Sharp Mind',
    'rankBrainRacer': 'Brain Racer',
    'rankLightningMind': 'Lightning Mind',
    'rankBrainMaster': 'Brain Master',
    'completed': 'COMPLETED',
    'fastAnswers': 'Fast answers',
    'firstBest': 'Your first personal best!',
    'beatBest': 'You beat your best by',
    'matchedBest': 'You matched your best!',
    'pointsToBest': 'Points to your best:',
    'totalXp': 'Total XP',
    'correctAnswer': 'Correct answer',
    'choose': 'Trust your first instinct.',
    'timesUp': "TIME’S UP!",
    'resultSubtitle': 'A little sharper with every rush.',
    'newBest': 'NEW PERSONAL BEST',
    'correctCount': 'Correct answers',
    'wrongCount': 'Wrong answers',
    'bestStreak': 'Best multiplier',
    'accuracy': 'Accuracy',
    'again': 'PLAY AGAIN',
    'home': 'HOME',
    'watch': 'WATCH AD · +20 seconds',
    'adHint': 'Extra time · coming soon',
    'dailyDetail': 'One fresh challenge. The same questions for everyone.',
    'todayBest': "Today’s best",
    'notPlayed': 'Your challenge is waiting',
    'playDaily': 'START DAILY CHALLENGE',
    'replayDaily': 'REPLAY CHALLENGE',
    'replayNote': 'Replays are open in V1. Your best result is saved.',
    'attemptsAvailable': 'attempts available today',
    'attemptsRemaining': 'attempts remaining',
    'attemptNumber': 'Attempt',
    'currentAttemptScore': 'This attempt',
    'yourRank': 'Your rank',
    'yourRankToday': 'Your rank today',
    'currentRank': 'Current Rank',
    'todayHighest': "Today’s highest",
    'attemptsTodayLabel': 'Attempts today',
    'attemptsUsedSemantics': '{count} of 3 attempts used today',
    'newChallengeTomorrow': 'New challenge tomorrow',
    'yourBest': 'Your best',
    'numberOneToday': "You’re #1 today",
    'attemptsToday': '{count} attempts today',
    'oneAttemptLeft': '1 attempt remaining',
    'twoAttemptsLeft': '2 attempts remaining',
    'rankOf': 'of',
    'topPercentToday': 'Top {percent}% today',
    'rankingLoading': 'Loading rank…',
    'rankingUnavailable': 'Ranking unavailable',
    'refreshRank': 'Refresh rank',
    'retryDaily': "Retry today's challenge",
    'watchAdToRetry': 'WATCH AD TO RETRY',
    'allAttemptsUsed': "You've used all 3 attempts today.",
    'tryTomorrow': 'Come back tomorrow for a new challenge.',
    'adUnavailable': 'Ad unavailable right now. Try again shortly.',
    'retryNotEarned': 'Watch the full ad to unlock a retry.',
    'purchaseChecking': 'Checking your Remove Ads purchase. Please wait.',
    'totalGames': 'Games played',
    'average': 'Average score',
    'longest': 'Longest correct streak',
    'statsSubtitle': 'Small sessions. Real momentum.',
    'language': 'Language',
    'english': 'English',
    'arabic': 'العربية',
    'sound': 'Sound',
    'soundHint': 'Short game effects only · no music',
    'haptics': 'Haptics',
    'theme': 'Appearance',
    'system': 'System',
    'dark': 'Dark',
    'light': 'Light',
    'privacy': 'Privacy Policy',
    'terms': 'Terms & Conditions',
    'helpSupport': 'Help & Support',
    'contactSupport': 'Contact Support',
    'supportSubject': 'Brain Rush Support',
    'appVersion': 'Version {version} ({build})',
    'supportUnavailable':
        'No email app is available. Support address copied: {email}',
    'legalUnavailable': 'Could not open the page. Please try again.',
    'supportGreeting': 'Hi Brain Rush team,',
    'supportPrompt': 'Please describe your issue here:',
    'supportInfo': 'App information',
    'supportApp': 'App',
    'supportVersion': 'Version',
    'supportBuild': 'Build',
    'supportPlatform': 'Platform',
    'supportOs': 'OS',
    'supportDevice': 'Device',
    'supportLanguage': 'Language',
    'restore': 'Restore Purchases',
    'placeholder': 'This feature will be available in a future release.',
    'privacyBody': 'Your name stays on this device. Daily ranking uses an anonymous ID and score. Results are shared only when you tap Share. Ads and purchases use their platform services. A full policy will be provided before release.',
    'termsBody': 'Brain Rush is a casual puzzle game. Remove Ads is a one-time store purchase. Store terms apply. Full terms are required before release.',
    'close': 'Close',
    'leave': 'Leave this rush?',
    'leaveBody': 'This round will end without saving a result.',
    'keepPlaying': 'KEEP PLAYING',
    'quit': 'LEAVE RUSH',
    'saveError': 'Could not save progress. Check device storage and try again.',
    'round': '60-SECOND RUSH',
    'dailyRound': 'DAILY RUSH',
    'ready': 'READY WHEN YOU ARE',
    'on': 'On',
    'off': 'Off',
    'points': 'points',
    'answer': 'Answer',
    'version': 'BRAIN RUSH / VERSION 1.0',
    'removeAds': 'REMOVE ADS',
    'explore': 'EXPLORE',
    'noInterstitials': 'No interstitial ads',
    'noForcedAds': 'Play without ad interruptions',
    'supportRush': 'Support Brain Rush',
    'oneTimePurchase': 'One-time purchase',
    'owned': 'Purchased',
    'adFreeActive': 'Ad-free — Active',
    'loadingPurchase': 'Loading purchase information…',
    'purchaseUnavailable': 'Purchase unavailable',
    'purchasePending': 'Purchase pending…',
    'purchaseRestored': 'Purchase restored',
    'noPurchases': 'No eligible purchase found',
    'storeUnavailable': 'Store temporarily unavailable. Try again later.',
    'privacyChoices': 'Privacy choices',
    'watchDoubleXp': 'Watch ad · Double XP',
    'claimXpBonus': 'CLAIM XP BONUS',
    'dailyBadge': 'A FRESH CHALLENGE, EVERY DAY',
    'welcome': 'Make Brain Rush yours',
    'chooseLanguage': 'Choose your language',
    'chooseLanguageHint': 'You can change it later in Settings.',
    'continue': 'CONTINUE',
    'skip': 'SKIP',
    'playerName': 'Player name',
    'playerNameHint': 'Optional · saved only on this device',
    'playerNamePlaceholder': 'What should we call you?',
    'nameRequired': 'Enter a name or choose Skip.',
    'nameTooLong': 'Use 20 characters or fewer.',
    'editName': 'Edit player name',
    'clearName': 'Remove name',
    'saveName': 'SAVE NAME',
    'readyNamed': 'Ready, {name}?',
    'newBestNamed': 'New best, {name}!',
    'numberOneNamed': "You’re #1 today, {name}!",
    'share': 'SHARE RESULT',
    'shareRushTitle': '60-SECOND RUSH',
    'shareDailyTitle': 'DAILY CHALLENGE',
    'shareScored': '{name} scored',
    'shareMyScore': 'I scored',
    'shareRushInvite': 'Can you beat my score?',
    'shareDailyInvite': 'Can you beat me today?',
    'shareRushCaption': 'I scored {score} in Brain Rush. Can you beat me?',
    'shareDailyCaption': "I’m #{rank} in today’s Brain Rush Daily Challenge. Can you beat my score?",
    'shareDailyNoRankCaption': 'I scored {score} in today’s Brain Rush Daily Challenge. Can you beat my score?',
    'shareUnavailable': 'Could not create the share image. Try again.',
  };
  static const ar = {
    'app': 'تحدي العقل في ٦٠ ثانية',
    'eyebrow': 'شرارة نشاطك الذهني اليومية',
    'sixty': '٦٠ ثانية',
    'brand': 'تحدي العقل',
    'tagline': 'ما مدى سرعة عقلك اليوم؟',
    'start': 'ابدأ التحدي',
    'best': 'أفضل نتيجة',
    'dailyStreak': 'أيام متتالية',
    'days': 'أيام',
    'daySingular': 'يوم',
    'daily': 'التحدي اليومي',
    'statistics': 'الإحصائيات',
    'settings': 'الإعدادات',
    'premium': 'إزالة الإعلانات',
    'premiumDetail': 'شراء لمرة واحدة · العب دون مقاطعة',
    'soon': 'قريبًا',
    'offline': '٦٠ ثانية. خمس طرق للتفكير. إمكانات بلا حدود.',
    'score': 'النتيجة',
    'timer': 'الوقت المتبقي',
    'streak': 'التتابع',
    'larger': 'أيهما أكبر؟',
    'smaller': 'أيهما أصغر؟',
    'fractionLarger': 'أي الكسرين أكبر؟',
    'fractionSmaller': 'أي الكسرين أصغر؟',
    'solve': 'أوجد الإجابة',
    'odd': 'أي الأعداد فردي؟',
    'even': 'أي الأعداد زوجي؟',
    'sequence': 'أكمل المتتالية',
    'type_larger': 'مقارنة سريعة',
    'type_arithmetic': 'حساب ذهني',
    'type_parity': 'فردي أم زوجي',
    'type_sequence': 'اكتشاف الأنماط',
    'type_fraction': 'تحدي الكسور',
    'correct': 'إجابة صحيحة!',
    'incorrect': 'واصل المحاولة!',
    'fast': 'سريع!',
    'lightning': 'خاطف!',
    'streakCallout': 'سلسلة رائعة!',
    'secondsShort': 'ث',
    'level': 'المستوى',
    'xp': 'نقطة خبرة',
    'levelUp': 'مستوى جديد!',
    'newRank': 'لقب جديد',
    'rankWarmUp': 'بداية قوية',
    'rankQuickThinker': 'سريع البديهة',
    'rankSharpMind': 'ذهن حاد',
    'rankBrainRacer': 'متسابق الأفكار',
    'rankLightningMind': 'ذهن خاطف',
    'rankBrainMaster': 'سيّد التحدي',
    'completed': 'مكتمل',
    'fastAnswers': 'إجابات سريعة',
    'firstBest': 'أول رقم قياسي لك!',
    'beatBest': 'تجاوزت أفضل نتيجة بفارق',
    'matchedBest': 'عادلت أفضل نتيجة لك!',
    'pointsToBest': 'نقاط تفصلك عن أفضل نتيجة:',
    'totalXp': 'مجموع الخبرة',
    'correctAnswer': 'الإجابة الصحيحة',
    'choose': 'ثق بحدسك الأول.',
    'timesUp': 'انتهى الوقت!',
    'resultSubtitle': 'مع كل تحدٍّ، تزداد مهارتك.',
    'newBest': 'رقم قياسي جديد',
    'correctCount': 'إجابات صحيحة',
    'wrongCount': 'إجابات خاطئة',
    'bestStreak': 'أفضل مضاعف',
    'accuracy': 'الدقة',
    'again': 'العب مجددًا',
    'home': 'الرئيسية',
    'watch': 'شاهد إعلانًا · ٢٠ ثانية إضافية',
    'adHint': 'وقت إضافي · قريبًا',
    'dailyDetail': 'تحدٍّ جديد كل يوم. الأسئلة نفسها للجميع.',
    'todayBest': 'أفضل نتيجة اليوم',
    'notPlayed': 'تحديك بانتظارك',
    'playDaily': 'ابدأ التحدي اليومي',
    'replayDaily': 'أعد التحدي',
    'replayNote': 'الإعادة متاحة حاليًا. نحفظ أفضل نتيجة لك.',
    'attemptsAvailable': 'محاولات متاحة اليوم',
    'attemptsRemaining': 'محاولات متبقية',
    'attemptNumber': 'المحاولة',
    'currentAttemptScore': 'نتيجة هذه المحاولة',
    'yourRank': 'ترتيبك',
    'yourRankToday': 'ترتيبك اليوم',
    'currentRank': 'الترتيب الحالي',
    'todayHighest': 'أعلى نتيجة اليوم',
    'attemptsTodayLabel': 'محاولات اليوم',
    'attemptsUsedSemantics': 'استخدمت {count} من 3 محاولات اليوم',
    'newChallengeTomorrow': 'تحدٍ جديد غداً',
    'yourBest': 'أفضل نتيجة لك',
    'numberOneToday': 'أنت الأول اليوم',
    'attemptsToday': '{count} محاولات اليوم',
    'oneAttemptLeft': 'محاولة واحدة متبقية',
    'twoAttemptsLeft': 'محاولتان متبقيتان',
    'rankOf': 'من',
    'topPercentToday': 'ضمن أفضل {percent}٪ اليوم',
    'rankingLoading': 'جارٍ تحميل الترتيب…',
    'rankingUnavailable': 'الترتيب غير متاح الآن',
    'refreshRank': 'تحديث الترتيب',
    'retryDaily': 'أعد تحدي اليوم',
    'watchAdToRetry': 'شاهد إعلانًا لإعادة المحاولة',
    'allAttemptsUsed': 'استخدمت محاولاتك الثلاث اليوم.',
    'tryTomorrow': 'عُد غدًا لتحدٍّ جديد.',
    'adUnavailable': 'الإعلان غير متاح الآن. حاول بعد قليل.',
    'retryNotEarned': 'شاهد الإعلان كاملًا لفتح محاولة جديدة.',
    'purchaseChecking': 'جارٍ التحقق من شراء إزالة الإعلانات. انتظر قليلًا.',
    'totalGames': 'الجولات المكتملة',
    'average': 'متوسط النتيجة',
    'longest': 'أطول تتابع صحيح',
    'statsSubtitle': 'جلسات قصيرة. تقدم مستمر.',
    'language': 'اللغة',
    'english': 'English',
    'arabic': 'العربية',
    'sound': 'الصوت',
    'soundHint': 'مؤثرات قصيرة فقط · بلا موسيقى',
    'haptics': 'الاهتزاز',
    'theme': 'المظهر',
    'system': 'النظام',
    'dark': 'داكن',
    'light': 'فاتح',
    'privacy': 'سياسة الخصوصية',
    'terms': 'الشروط والأحكام',
    'helpSupport': 'المساعدة والدعم',
    'contactSupport': 'تواصل مع الدعم',
    'supportSubject': 'دعم Brain Rush',
    'appVersion': 'الإصدار {version} ({build})',
    'supportUnavailable':
        'لا يوجد تطبيق بريد إلكتروني. تم نسخ عنوان الدعم: {email}',
    'legalUnavailable': 'تعذر فتح الصفحة. حاول مرة أخرى.',
    'supportGreeting': 'مرحباً فريق Brain Rush،',
    'supportPrompt': 'يرجى كتابة المشكلة هنا:',
    'supportInfo': 'معلومات التطبيق',
    'supportApp': 'التطبيق',
    'supportVersion': 'الإصدار',
    'supportBuild': 'رقم البناء',
    'supportPlatform': 'النظام',
    'supportOs': 'إصدار النظام',
    'supportDevice': 'الجهاز',
    'supportLanguage': 'اللغة',
    'restore': 'استعادة المشتريات',
    'placeholder': 'ستتوفر هذه الميزة في إصدار قادم.',
    'privacyBody': 'يبقى اسمك على هذا الجهاز فقط. يستخدم الترتيب اليومي معرّفًا مجهولًا ونتيجتك. لا تُشارك النتائج إلا عندما تضغط مشاركة. تستخدم الإعلانات والمشتريات خدمات منصاتها. ستتوفر سياسة كاملة قبل النشر.',
    'termsBody': 'تحدي العقل لعبة ألغاز للترفيه. إزالة الإعلانات شراء لمرة واحدة عبر المتجر. تنطبق شروط المتجر. يجب إضافة الشروط الكاملة قبل النشر.',
    'close': 'إغلاق',
    'leave': 'مغادرة التحدي؟',
    'leaveBody': 'ستنتهي الجولة دون حفظ النتيجة.',
    'keepPlaying': 'متابعة اللعب',
    'quit': 'مغادرة',
    'saveError': 'تعذر حفظ تقدمك. تحقق من مساحة الجهاز وحاول مجددًا.',
    'round': 'تحدي ٦٠ ثانية',
    'dailyRound': 'التحدي اليومي',
    'ready': 'جاهز عندما تكون مستعدًا',
    'on': 'تشغيل',
    'off': 'إيقاف',
    'points': 'نقطة',
    'answer': 'إجابة',
    'version': 'تحدي العقل / الإصدار ١٫٠',
    'removeAds': 'إزالة الإعلانات',
    'explore': 'اكتشف',
    'noInterstitials': 'بلا إعلانات بين الجولات',
    'noForcedAds': 'العب دون مقاطعات إعلانية',
    'supportRush': 'ادعم تحدي العقل',
    'oneTimePurchase': 'شراء لمرة واحدة',
    'owned': 'تم الشراء',
    'adFreeActive': 'بدون إعلانات — مفعّل',
    'loadingPurchase': 'جارٍ تحميل معلومات الشراء…',
    'purchaseUnavailable': 'الشراء غير متاح',
    'purchasePending': 'عملية الشراء قيد الانتظار…',
    'purchaseRestored': 'تمت استعادة المشتريات',
    'noPurchases': 'لم نعثر على مشتريات قابلة للاستعادة',
    'storeUnavailable': 'المتجر غير متاح مؤقتًا. حاول لاحقًا.',
    'privacyChoices': 'خيارات الخصوصية',
    'watchDoubleXp': 'شاهد إعلانًا · ضاعف الخبرة',
    'claimXpBonus': 'احصل على الخبرة الإضافية',
    'dailyBadge': 'تحدٍّ جديد كل يوم',
    'welcome': 'اجعل تحدي العقل على طريقتك',
    'chooseLanguage': 'اختر لغتك',
    'chooseLanguageHint': 'يمكنك تغييرها لاحقًا من الإعدادات.',
    'continue': 'متابعة',
    'skip': 'تخطي',
    'playerName': 'اسم اللاعب',
    'playerNameHint': 'اختياري · يُحفظ على هذا الجهاز فقط',
    'playerNamePlaceholder': 'بماذا نناديك؟',
    'nameRequired': 'أدخل اسمًا أو اختر تخطي.',
    'nameTooLong': 'استخدم ٢٠ حرفًا أو أقل.',
    'editName': 'تعديل اسم اللاعب',
    'clearName': 'حذف الاسم',
    'saveName': 'حفظ الاسم',
    'readyNamed': 'جاهز يا {name}؟',
    'newBestNamed': 'رقم قياسي جديد يا {name}!',
    'numberOneNamed': 'أنت الأول اليوم يا {name}!',
    'share': 'مشاركة النتيجة',
    'shareRushTitle': 'تحدي ٦٠ ثانية',
    'shareDailyTitle': 'التحدي اليومي',
    'shareScored': 'نتيجة {name}',
    'shareMyScore': 'حققت',
    'shareRushInvite': 'هل تستطيع تجاوز نتيجتي؟',
    'shareDailyInvite': 'هل تستطيع التفوق عليّ اليوم؟',
    'shareRushCaption': 'حققت {score} في تحدي العقل. هل تستطيع تجاوز نتيجتي؟',
    'shareDailyCaption':
        'ترتيبي #{rank} في تحدي العقل اليومي. هل تستطيع تجاوز نتيجتي؟',
    'shareDailyNoRankCaption':
        'حققت {score} في تحدي العقل اليومي. هل تستطيع تجاوز نتيجتي؟',
    'shareUnavailable': 'تعذر إنشاء صورة المشاركة. حاول مجددًا.',
  };
}

extension LocalizedContext on BuildContext {
  String tr(String key) => Strings.of(this).t(key);
}
