import 'package:flutter/material.dart';

class Strings {
  Strings(this.locale);
  final String locale;
  String dayCount(int count) {
    if (locale != 'ar') return '$count ${count == 1 ? 'day' : 'days'}';
    if (count == 1) return 'يوم واحد';
    if (count == 2) return 'يومان';
    return '$count ${count == 0 || count % 100 >= 3 && count % 100 <= 10 ? 'أيام' : 'يومًا'}';
  }

  static Strings of(BuildContext context) =>
      Strings(Localizations.localeOf(context).languageCode);
  String t(String key) => (locale == 'ar' ? ar : en)[key] ?? en[key] ?? key;
  static const en = {
    'app': '60-Second Brain Rush',
    'eyebrow': 'YOUR DAILY MENTAL SPARK',
    'sixty': '60 SECOND',
    'brand': 'BRAIN RUSH',
    'tagline': 'How fast is your brain today?',
    'start': 'START RUSH',
    'best': 'Best score',
    'dailyStreak': 'Daily streak',
    'days': 'days',
    'daily': 'Daily Challenge',
    'statistics': 'Statistics',
    'settings': 'Settings',
    'premium': 'REMOVE ADS',
    'premiumDetail': 'One-time purchase · play without interruptions',
    'soon': 'COMING SOON',
    'offline': '60 seconds. Five ways to think. Endless possibility.',
    'score': 'Score',
    'timer': 'Time left',
    'streak': 'Streak',
    'larger': 'Which is larger?',
    'smaller': 'Which is smaller?',
    'fractionLarger': 'Which fraction is larger?',
    'fractionSmaller': 'Which fraction is smaller?',
    'solve': 'Find the answer',
    'odd': 'Which number is odd?',
    'even': 'Which number is even?',
    'sequence': 'Complete the sequence',
    'type_larger': 'QUICK COMPARE',
    'type_arithmetic': 'MENTAL MATH',
    'type_parity': 'ODD OR EVEN',
    'type_sequence': 'PATTERN FINDER',
    'type_fraction': 'FRACTION SPRINT',
    'correct': 'Correct!',
    'incorrect': 'Keep going!',
    'fast': 'FAST!',
    'lightning': 'LIGHTNING!',
    'streakCallout': 'STREAK!',
    'secondsShort': 'SEC',
    'level': 'LV.',
    'xp': 'XP',
    'levelUp': 'LEVEL UP!',
    'newRank': 'NEW RANK',
    'rankWarmUp': 'Warm-Up',
    'rankQuickThinker': 'Quick Thinker',
    'rankSharpMind': 'Sharp Mind',
    'rankBrainRacer': 'Brain Racer',
    'rankLightningMind': 'Lightning Mind',
    'rankBrainMaster': 'Brain Master',
    'completed': 'COMPLETED',
    'fastAnswers': 'Fast answers',
    'firstBest': 'Your first personal best!',
    'beatBest': 'You beat your best by',
    'matchedBest': 'You matched your best!',
    'pointsToBest': 'Points to your best:',
    'totalXp': 'Total XP',
    'correctAnswer': 'Correct answer',
    'choose': 'Trust your first instinct.',
    'timesUp': "TIME’S UP!",
    'resultSubtitle': 'A little sharper with every rush.',
    'newBest': 'NEW PERSONAL BEST',
    'correctCount': 'Correct answers',
    'wrongCount': 'Wrong answers',
    'bestStreak': 'Best multiplier',
    'accuracy': 'Accuracy',
    'again': 'PLAY AGAIN',
    'home': 'HOME',
    'watch': 'WATCH AD · +20 seconds',
    'adHint': 'Extra time · coming soon',
    'dailyDetail': 'One fresh challenge. The same questions for everyone.',
    'todayBest': "Today’s best",
    'notPlayed': 'Your challenge is waiting',
    'playDaily': 'START DAILY CHALLENGE',
    'replayDaily': 'REPLAY CHALLENGE',
    'replayNote': 'Replays are open in V1. Your best result is saved.',
    'totalGames': 'Games played',
    'average': 'Average score',
    'longest': 'Longest correct streak',
    'statsSubtitle': 'Small sessions. Real momentum.',
    'language': 'Language',
    'english': 'English',
    'arabic': 'العربية',
    'sound': 'Sound',
    'soundHint': 'Short game effects only · no music',
    'haptics': 'Haptics',
    'theme': 'Appearance',
    'system': 'System',
    'dark': 'Dark',
    'light': 'Light',
    'privacy': 'Privacy Policy',
    'terms': 'Terms',
    'restore': 'Restore Purchases',
    'placeholder': 'This feature will be available in a future release.',
    'privacyBody': 'Scores and settings stay on this device. Ads use Google Mobile Ads when consent allows. Purchases are handled by the app store. A full privacy policy is required before release.',
    'termsBody': 'Brain Rush is a casual puzzle game. Remove Ads is a one-time store purchase. Store terms apply. Full terms are required before release.',
    'close': 'Close',
    'leave': 'Leave this rush?',
    'leaveBody': 'This round will end without saving a result.',
    'keepPlaying': 'KEEP PLAYING',
    'quit': 'LEAVE RUSH',
    'saveError': 'Could not save progress. Check device storage and try again.',
    'round': '60-SECOND RUSH',
    'dailyRound': 'DAILY RUSH',
    'ready': 'READY WHEN YOU ARE',
    'on': 'On',
    'off': 'Off',
    'points': 'points',
    'answer': 'Answer',
    'version': 'BRAIN RUSH / VERSION 1.0',
    'removeAds': 'REMOVE ADS',
    'explore': 'EXPLORE',
    'noInterstitials': 'No interstitial ads',
    'noForcedAds': 'Play without ad interruptions',
    'supportRush': 'Support Brain Rush',
    'oneTimePurchase': 'One-time purchase',
    'owned': 'Purchased',
    'loadingPurchase': 'Loading purchase information…',
    'purchaseUnavailable': 'Purchase unavailable',
    'purchasePending': 'Purchase pending…',
    'purchaseRestored': 'Purchase restored',
    'noPurchases': 'No eligible purchase found',
    'storeUnavailable': 'Store temporarily unavailable. Try again later.',
    'privacyChoices': 'Privacy choices',
    'watchDoubleXp': 'Watch ad · Double XP',
    'claimXpBonus': 'CLAIM XP BONUS',
    'dailyBadge': 'A FRESH CHALLENGE, EVERY DAY',
  };
  static const ar = {
    'app': 'تحدي العقل في ٦٠ ثانية',
    'eyebrow': 'شرارة نشاطك الذهني اليومية',
    'sixty': '٦٠ ثانية',
    'brand': 'تحدي العقل',
    'tagline': 'ما مدى سرعة عقلك اليوم؟',
    'start': 'ابدأ التحدي',
    'best': 'أفضل نتيجة',
    'dailyStreak': 'أيام متتالية',
    'days': 'أيام',
    'daily': 'التحدي اليومي',
    'statistics': 'الإحصائيات',
    'settings': 'الإعدادات',
    'premium': 'إزالة الإعلانات',
    'premiumDetail': 'شراء لمرة واحدة · العب دون مقاطعة',
    'soon': 'قريبًا',
    'offline': '٦٠ ثانية. خمس طرق للتفكير. إمكانات بلا حدود.',
    'score': 'النتيجة',
    'timer': 'الوقت المتبقي',
    'streak': 'التتابع',
    'larger': 'أيهما أكبر؟',
    'smaller': 'أيهما أصغر؟',
    'fractionLarger': 'أي الكسرين أكبر؟',
    'fractionSmaller': 'أي الكسرين أصغر؟',
    'solve': 'أوجد الإجابة',
    'odd': 'أي الأعداد فردي؟',
    'even': 'أي الأعداد زوجي؟',
    'sequence': 'أكمل المتتالية',
    'type_larger': 'مقارنة سريعة',
    'type_arithmetic': 'حساب ذهني',
    'type_parity': 'فردي أم زوجي',
    'type_sequence': 'اكتشاف الأنماط',
    'type_fraction': 'تحدي الكسور',
    'correct': 'إجابة صحيحة!',
    'incorrect': 'واصل المحاولة!',
    'fast': 'سريع!',
    'lightning': 'خاطف!',
    'streakCallout': 'سلسلة رائعة!',
    'secondsShort': 'ث',
    'level': 'المستوى',
    'xp': 'نقطة خبرة',
    'levelUp': 'مستوى جديد!',
    'newRank': 'لقب جديد',
    'rankWarmUp': 'بداية قوية',
    'rankQuickThinker': 'سريع البديهة',
    'rankSharpMind': 'ذهن حاد',
    'rankBrainRacer': 'متسابق الأفكار',
    'rankLightningMind': 'ذهن خاطف',
    'rankBrainMaster': 'سيّد التحدي',
    'completed': 'مكتمل',
    'fastAnswers': 'إجابات سريعة',
    'firstBest': 'أول رقم قياسي لك!',
    'beatBest': 'تجاوزت أفضل نتيجة بفارق',
    'matchedBest': 'عادلت أفضل نتيجة لك!',
    'pointsToBest': 'نقاط تفصلك عن أفضل نتيجة:',
    'totalXp': 'مجموع الخبرة',
    'correctAnswer': 'الإجابة الصحيحة',
    'choose': 'ثق بحدسك الأول.',
    'timesUp': 'انتهى الوقت!',
    'resultSubtitle': 'مع كل تحدٍّ، تزداد مهارتك.',
    'newBest': 'رقم قياسي جديد',
    'correctCount': 'إجابات صحيحة',
    'wrongCount': 'إجابات خاطئة',
    'bestStreak': 'أفضل مضاعف',
    'accuracy': 'الدقة',
    'again': 'العب مجددًا',
    'home': 'الرئيسية',
    'watch': 'شاهد إعلانًا · ٢٠ ثانية إضافية',
    'adHint': 'وقت إضافي · قريبًا',
    'dailyDetail': 'تحدٍّ جديد كل يوم. الأسئلة نفسها للجميع.',
    'todayBest': 'أفضل نتيجة اليوم',
    'notPlayed': 'تحديك بانتظارك',
    'playDaily': 'ابدأ التحدي اليومي',
    'replayDaily': 'أعد التحدي',
    'replayNote': 'الإعادة متاحة حاليًا. نحفظ أفضل نتيجة لك.',
    'totalGames': 'الجولات المكتملة',
    'average': 'متوسط النتيجة',
    'longest': 'أطول تتابع صحيح',
    'statsSubtitle': 'جلسات قصيرة. تقدم مستمر.',
    'language': 'اللغة',
    'english': 'English',
    'arabic': 'العربية',
    'sound': 'الصوت',
    'soundHint': 'مؤثرات قصيرة فقط · بلا موسيقى',
    'haptics': 'الاهتزاز',
    'theme': 'المظهر',
    'system': 'النظام',
    'dark': 'داكن',
    'light': 'فاتح',
    'privacy': 'سياسة الخصوصية',
    'terms': 'الشروط',
    'restore': 'استعادة المشتريات',
    'placeholder': 'ستتوفر هذه الميزة في إصدار قادم.',
    'privacyBody': 'تبقى نتائجك وإعداداتك على هذا الجهاز. تستخدم الإعلانات خدمات Google عند السماح بها. يعالج المتجر عمليات الشراء. يجب إضافة سياسة خصوصية كاملة قبل النشر.',
    'termsBody': 'تحدي العقل لعبة ألغاز للترفيه. إزالة الإعلانات شراء لمرة واحدة عبر المتجر. تنطبق شروط المتجر. يجب إضافة الشروط الكاملة قبل النشر.',
    'close': 'إغلاق',
    'leave': 'مغادرة التحدي؟',
    'leaveBody': 'ستنتهي الجولة دون حفظ النتيجة.',
    'keepPlaying': 'متابعة اللعب',
    'quit': 'مغادرة',
    'saveError': 'تعذر حفظ تقدمك. تحقق من مساحة الجهاز وحاول مجددًا.',
    'round': 'تحدي ٦٠ ثانية',
    'dailyRound': 'التحدي اليومي',
    'ready': 'جاهز عندما تكون مستعدًا',
    'on': 'تشغيل',
    'off': 'إيقاف',
    'points': 'نقطة',
    'answer': 'إجابة',
    'version': 'تحدي العقل / الإصدار ١٫٠',
    'removeAds': 'إزالة الإعلانات',
    'explore': 'اكتشف',
    'noInterstitials': 'بلا إعلانات بين الجولات',
    'noForcedAds': 'العب دون مقاطعات إعلانية',
    'supportRush': 'ادعم تحدي العقل',
    'oneTimePurchase': 'شراء لمرة واحدة',
    'owned': 'تم الشراء',
    'loadingPurchase': 'جارٍ تحميل معلومات الشراء…',
    'purchaseUnavailable': 'الشراء غير متاح',
    'purchasePending': 'عملية الشراء قيد الانتظار…',
    'purchaseRestored': 'تمت استعادة المشتريات',
    'noPurchases': 'لم نعثر على مشتريات قابلة للاستعادة',
    'storeUnavailable': 'المتجر غير متاح مؤقتًا. حاول لاحقًا.',
    'privacyChoices': 'خيارات الخصوصية',
    'watchDoubleXp': 'شاهد إعلانًا · ضاعف الخبرة',
    'claimXpBonus': 'احصل على الخبرة الإضافية',
    'dailyBadge': 'تحدٍّ جديد كل يوم',
  };
}

extension LocalizedContext on BuildContext {
  String tr(String key) => Strings.of(this).t(key);
}
