/// Short, local-only copy for the Daily Challenge reminder and its opt-in UI.
class ReminderStrings {
  const ReminderStrings(this.language);
  final String language;

  static const Map<String, Map<String, String>> all = {
    'en': {
      'setting': 'Daily Challenge Reminder',
      'optInTitle': 'Never miss today’s challenge',
      'optInBody': 'Get one reminder around 1 PM if you haven’t played today.',
      'enable': 'Enable reminders',
      'notNow': 'Not now',
      'disabled': 'Notifications are off in system settings.',
      'notificationTitle': 'Brain Rush Daily Challenge',
      'notificationBody': 'Your Daily Challenge is waiting 🧠',
      'notificationBodyNamed': '{name}, your Daily Challenge is waiting 🧠',
      'channelName': 'Daily Challenge',
      'channelDescription': 'A reminder for your unplayed Daily Challenge',
    },
    'ar': {
      'setting': 'تذكير التحدي اليومي',
      'optInTitle': 'لا تفوّت تحدي اليوم',
      'optInBody': 'سنذكّرك نحو الساعة ١ ظهرًا إذا لم تلعب تحدي اليوم.',
      'enable': 'تفعيل التذكيرات',
      'notNow': 'ليس الآن',
      'disabled': 'الإشعارات معطّلة في إعدادات الجهاز.',
      'notificationTitle': 'تحدي Brain Rush اليومي',
      'notificationBody': 'تحدي Brain Rush اليومي بانتظارك 🧠',
      'notificationBodyNamed': '{name}، تحدي Brain Rush اليومي بانتظارك 🧠',
      'channelName': 'التحدي اليومي',
      'channelDescription': 'تذكير بالتحدي اليومي إذا لم تلعبه',
    },
    'es': {
      'setting': 'Recordatorio del reto diario',
      'optInTitle': 'No te pierdas el reto de hoy',
      'optInBody': 'Te avisaremos sobre la 1 p. m. si aún no has jugado.',
      'enable': 'Activar recordatorios',
      'notNow': 'Ahora no',
      'disabled': 'Las notificaciones están desactivadas en el dispositivo.',
      'notificationTitle': 'Reto diario de Brain Rush',
      'notificationBody': 'Tu reto diario te espera 🧠',
      'notificationBodyNamed': '{name}, tu reto diario te espera 🧠',
      'channelName': 'Reto diario',
      'channelDescription': 'Un aviso si aún no jugaste el reto diario',
    },
    'pt_BR': {
      'setting': 'Lembrete do desafio diário',
      'optInTitle': 'Não perca o desafio de hoje',
      'optInBody': 'Avisaremos por volta das 13h se você ainda não jogou.',
      'enable': 'Ativar lembretes',
      'notNow': 'Agora não',
      'disabled': 'As notificações estão desativadas no aparelho.',
      'notificationTitle': 'Desafio diário Brain Rush',
      'notificationBody': 'Seu desafio diário está esperando 🧠',
      'notificationBodyNamed': '{name}, seu desafio diário está esperando 🧠',
      'channelName': 'Desafio diário',
      'channelDescription': 'Aviso para o desafio diário não jogado',
    },
    'fr': {
      'setting': 'Rappel du défi quotidien',
      'optInTitle': 'Ne manquez pas le défi du jour',
      'optInBody': 'Un rappel vers 13 h si vous n’avez pas encore joué.',
      'enable': 'Activer les rappels',
      'notNow': 'Plus tard',
      'disabled': 'Les notifications sont désactivées dans les réglages.',
      'notificationTitle': 'Défi quotidien Brain Rush',
      'notificationBody': 'Votre défi quotidien vous attend 🧠',
      'notificationBodyNamed': '{name}, votre défi quotidien vous attend 🧠',
      'channelName': 'Défi quotidien',
      'channelDescription': 'Rappel si le défi du jour reste à jouer',
    },
    'de': {
      'setting': 'Erinnerung an die Tagesaufgabe',
      'optInTitle': 'Verpass die heutige Aufgabe nicht',
      'optInBody':
          'Gegen 13 Uhr erinnern wir dich, falls du noch nicht gespielt hast.',
      'enable': 'Erinnerungen aktivieren',
      'notNow': 'Jetzt nicht',
      'disabled': 'Benachrichtigungen sind in den Geräteeinstellungen aus.',
      'notificationTitle': 'Brain Rush Tagesaufgabe',
      'notificationBody': 'Deine Tagesaufgabe wartet 🧠',
      'notificationBodyNamed': '{name}, deine Tagesaufgabe wartet 🧠',
      'channelName': 'Tagesaufgabe',
      'channelDescription': 'Erinnerung an die noch offene Tagesaufgabe',
    },
    'it': {
      'setting': 'Promemoria sfida quotidiana',
      'optInTitle': 'Non perdere la sfida di oggi',
      'optInBody': 'Un promemoria verso le 13 se non hai ancora giocato.',
      'enable': 'Attiva promemoria',
      'notNow': 'Non ora',
      'disabled': 'Le notifiche sono disattivate nelle impostazioni.',
      'notificationTitle': 'Sfida quotidiana Brain Rush',
      'notificationBody': 'La tua sfida quotidiana ti aspetta 🧠',
      'notificationBodyNamed': '{name}, la tua sfida quotidiana ti aspetta 🧠',
      'channelName': 'Sfida quotidiana',
      'channelDescription': 'Promemoria per la sfida quotidiana non giocata',
    },
    'tr': {
      'setting': 'Günlük görev hatırlatıcısı',
      'optInTitle': 'Bugünkü görevi kaçırma',
      'optInBody': 'Henüz oynamadıysan saat 13.00 civarında hatırlatalım.',
      'enable': 'Hatırlatıcıları aç',
      'notNow': 'Şimdi değil',
      'disabled': 'Bildirimler cihaz ayarlarında kapalı.',
      'notificationTitle': 'Brain Rush Günlük Görev',
      'notificationBody': 'Günlük görevin seni bekliyor 🧠',
      'notificationBodyNamed': '{name}, günlük görevin seni bekliyor 🧠',
      'channelName': 'Günlük Görev',
      'channelDescription': 'Oynanmayan günlük görev için hatırlatma',
    },
    'ru': {
      'setting': 'Напоминание о ежедневном задании',
      'optInTitle': 'Не пропустите задание дня',
      'optInBody': 'Напомним около 13:00, если вы ещё не играли.',
      'enable': 'Включить напоминания',
      'notNow': 'Не сейчас',
      'disabled': 'Уведомления отключены в настройках устройства.',
      'notificationTitle': 'Ежедневное задание Brain Rush',
      'notificationBody': 'Ваше ежедневное задание ждёт 🧠',
      'notificationBodyNamed': '{name}, ваше ежедневное задание ждёт 🧠',
      'channelName': 'Ежедневное задание',
      'channelDescription': 'Напоминание о непройденном задании дня',
    },
    'id': {
      'setting': 'Pengingat Tantangan Harian',
      'optInTitle': 'Jangan lewatkan tantangan hari ini',
      'optInBody': 'Kami ingatkan sekitar pukul 13.00 jika kamu belum bermain.',
      'enable': 'Aktifkan pengingat',
      'notNow': 'Nanti saja',
      'disabled': 'Notifikasi dimatikan di pengaturan perangkat.',
      'notificationTitle': 'Tantangan Harian Brain Rush',
      'notificationBody': 'Tantangan harianmu menunggu 🧠',
      'notificationBodyNamed': '{name}, tantangan harianmu menunggu 🧠',
      'channelName': 'Tantangan Harian',
      'channelDescription': 'Pengingat jika tantangan harian belum dimainkan',
    },
    'hi': {
      'setting': 'दैनिक चुनौती रिमाइंडर',
      'optInTitle': 'आज की चुनौती न चूकें',
      'optInBody': 'अगर आपने नहीं खेला, तो लगभग दोपहर 1 बजे याद दिलाएँगे।',
      'enable': 'रिमाइंडर चालू करें',
      'notNow': 'अभी नहीं',
      'disabled': 'डिवाइस सेटिंग में सूचनाएँ बंद हैं।',
      'notificationTitle': 'Brain Rush दैनिक चुनौती',
      'notificationBody': 'आपकी दैनिक चुनौती इंतज़ार कर रही है 🧠',
      'notificationBodyNamed': '{name}, आपकी दैनिक चुनौती इंतज़ार कर रही है 🧠',
      'channelName': 'दैनिक चुनौती',
      'channelDescription': 'आज की अधूरी चुनौती का रिमाइंडर',
    },
    'ja': {
      'setting': 'デイリーチャレンジの通知',
      'optInTitle': '今日のチャレンジを忘れずに',
      'optInBody': '未プレイなら午後1時ごろにお知らせします。',
      'enable': '通知をオンにする',
      'notNow': '今はしない',
      'disabled': '端末の設定で通知がオフになっています。',
      'notificationTitle': 'Brain Rush デイリーチャレンジ',
      'notificationBody': '今日のチャレンジが待っています 🧠',
      'notificationBodyNamed': '{name}さん、今日のチャレンジが待っています 🧠',
      'channelName': 'デイリーチャレンジ',
      'channelDescription': '未プレイのデイリーチャレンジをお知らせ',
    },
    'ko': {
      'setting': '일일 도전 알림',
      'optInTitle': '오늘의 도전을 놓치지 마세요',
      'optInBody': '아직 플레이하지 않았다면 오후 1시쯤 알려드려요.',
      'enable': '알림 켜기',
      'notNow': '나중에',
      'disabled': '기기 설정에서 알림이 꺼져 있어요.',
      'notificationTitle': 'Brain Rush 일일 도전',
      'notificationBody': '오늘의 도전이 기다리고 있어요 🧠',
      'notificationBodyNamed': '{name}님, 오늘의 도전이 기다리고 있어요 🧠',
      'channelName': '일일 도전',
      'channelDescription': '아직 하지 않은 일일 도전 알림',
    },
    'zh_Hans': {
      'setting': '每日挑战提醒',
      'optInTitle': '别错过今天的挑战',
      'optInBody': '如果你还没玩，我们会在下午1点左右提醒你。',
      'enable': '开启提醒',
      'notNow': '暂不',
      'disabled': '设备设置中已关闭通知。',
      'notificationTitle': 'Brain Rush 每日挑战',
      'notificationBody': '你的每日挑战还在等你 🧠',
      'notificationBodyNamed': '{name}，你的每日挑战还在等你 🧠',
      'channelName': '每日挑战',
      'channelDescription': '未完成每日挑战时提醒',
    },
    'zh_Hant': {
      'setting': '每日挑戰提醒',
      'optInTitle': '別錯過今天的挑戰',
      'optInBody': '如果你還沒玩，我們會在下午1點左右提醒你。',
      'enable': '開啟提醒',
      'notNow': '暫時不要',
      'disabled': '裝置設定中已關閉通知。',
      'notificationTitle': 'Brain Rush 每日挑戰',
      'notificationBody': '你的每日挑戰還在等你 🧠',
      'notificationBodyNamed': '{name}，你的每日挑戰還在等你 🧠',
      'channelName': '每日挑戰',
      'channelDescription': '未完成每日挑戰時提醒',
    },
    'ur': {
      'setting': 'روزانہ چیلنج کی یاددہانی',
      'optInTitle': 'آج کا چیلنج مت چھوڑیں',
      'optInBody': 'اگر آپ نے نہیں کھیلا تو دوپہر ۱ بجے کے قریب یاد دلائیں گے۔',
      'enable': 'یاددہانیاں فعال کریں',
      'notNow': 'ابھی نہیں',
      'disabled': 'ڈیوائس کی ترتیبات میں اطلاعات بند ہیں۔',
      'notificationTitle': 'Brain Rush روزانہ چیلنج',
      'notificationBody': 'آپ کا روزانہ چیلنج منتظر ہے 🧠',
      'notificationBodyNamed': '{name}، آپ کا روزانہ چیلنج منتظر ہے 🧠',
      'channelName': 'روزانہ چیلنج',
      'channelDescription': 'نہ کھیلے گئے روزانہ چیلنج کی یاددہانی',
    },
    'fa': {
      'setting': 'یادآور چالش روزانه',
      'optInTitle': 'چالش امروز را از دست ندهید',
      'optInBody': 'اگر هنوز بازی نکرده‌اید، حدود ساعت ۱۳ یادآوری می‌کنیم.',
      'enable': 'فعال‌کردن یادآورها',
      'notNow': 'فعلاً نه',
      'disabled': 'اعلان‌ها در تنظیمات دستگاه غیرفعال‌اند.',
      'notificationTitle': 'چالش روزانه Brain Rush',
      'notificationBody': 'چالش روزانه‌تان منتظر شماست 🧠',
      'notificationBodyNamed': '{name}، چالش روزانه‌تان منتظر شماست 🧠',
      'channelName': 'چالش روزانه',
      'channelDescription': 'یادآور چالش روزانه‌ای که بازی نشده است',
    },
    'bn': {
      'setting': 'দৈনিক চ্যালেঞ্জের স্মরণিকা',
      'optInTitle': 'আজকের চ্যালেঞ্জ মিস করবেন না',
      'optInBody': 'এখনও না খেললে দুপুর ১টার দিকে মনে করিয়ে দেব।',
      'enable': 'স্মরণিকা চালু করুন',
      'notNow': 'এখন নয়',
      'disabled': 'ডিভাইসের সেটিংসে বিজ্ঞপ্তি বন্ধ আছে।',
      'notificationTitle': 'Brain Rush দৈনিক চ্যালেঞ্জ',
      'notificationBody': 'আপনার দৈনিক চ্যালেঞ্জ অপেক্ষায় আছে 🧠',
      'notificationBodyNamed': '{name}, আপনার দৈনিক চ্যালেঞ্জ অপেক্ষায় আছে 🧠',
      'channelName': 'দৈনিক চ্যালেঞ্জ',
      'channelDescription': 'না খেলা দৈনিক চ্যালেঞ্জের স্মরণিকা',
    },
  };

  String t(String key) => all[language]?[key] ?? all['en']![key] ?? key;

  String notificationBody([String? name]) =>
      t(name == null ? 'notificationBody' : 'notificationBodyNamed')
          .replaceAll('{name}', name ?? '');
}
